logic for Cred budgets on Weighted Graphs
sourcecred/sourcecred pull request #2512
Opened 2020-11-14 00:33 UTC by decentralion

This commit adds core logic for applying a CredBudget to a
WeightedGraph. The idea is the budget sets constraints on how much Cred
nodes matching a given address can mint each interval. If the budget
constraint is violated in a particular period, all of the nodes created
in that period will be re-weighted to enforce the budget.

Test plan: Has some end-to-end unit tests and some helper unit tests,
but may still merit more testing as the logic is somewhat complex.

2020-11-17 22:21 UTC, blueridger requested changes

2020-11-21 01:54 UTC, decentralion commented on src/core/mintBudget.js
> +  let currentIndex = -1;
Sure, changed. I'm keeping the helper method since it's tested.

2020-11-21 01:55 UTC, decentralion commented on src/core/mintBudget.js
> +    const budget = _findCurrentBudget(periods, interval.startTimeMs);
Yeah, that was bugging me too. Changed to budgetValue

2020-11-21 01:58 UTC, decentralion commented on src/core/mintBudget.js
> +  return {graph: wg.graph, weights: newWeights};
I think it's fine tbh, but I don't mind changing it.

2020-11-23 19:11 UTC, blueridger approved these changes

2020-11-23 19:11 UTC, blueridger commented on src/core/mintBudget.js
> +    const budget = _findCurrentBudgetValue(periods, interval.startTimeMs);
didn't get changed to budgetValue

2020-11-23 19:11 UTC, blueridger commented on src/core/mintBudget.js
> +  budget: number
didn't get changed to budgetValue

2020-11-23 21:49 UTC, decentralion commented on src/core/mintBudget.js
> +    const budget = _findCurrentBudgetValue(periods, interval.startTimeMs);
Fixed.

2020-11-23 21:49 UTC, decentralion commented on src/core/mintBudget.js
> +  budget: number
Fixed.

2020-11-23 22:03 UTC, merged