Add ignoreActiveStatus option to Special Distributions
sourcecred/sourcecred pull request #3146
Opened 2021-08-19 18:57 UTC by blueridger

# Description
The Special Distribution type hasn't been publicly endorsed because it breaks "Grain comes from Cred." However, now that it is possible to include Special Distributions in the grain config, it may actually be a very nice solution to the question of "how does sourcecred work when some people are getting fixed salaries?" This is a reality of most organizations and probably will be for some time, and with good reason--it prioritizes meeting human needs, unlike our purely meritocratic paradigm.

The target use case for this PR: People with fixed salaries can be paid through special distributions instead of being paid outside of the sourcecred system, so that if they ever stop being salaried and want to earn normal grain, the Balanced policy will be aware of their previous pay and will not try to "catch them up" unless they actually were underpaid.

This is something the upcoming Product circle will likely dogfood.

# Test Plan
- regression tested the Special Distribution UI page at `/special-distribution`
- Tested on sourcecred/cred/gh-pages with `scdev graph -s -f`
### Regression test grain config with active account
Input:
```
{
  "allocationPolicies": [
    {
      "policyType": "SPECIAL",
      "memo": "test",
      "budget": 1000,
      "recipient": "6wyPOVWLmZ2b35eCmOrz1w"
    }
  ],
  "maxSimultaneousDistributions": 100
}

```
Output:
```
SPECIAL Policy
Budget 1,000.000g
Memo: test
Recepient: 6wyPOVWLmZ2b35eCmOrz1w
|          name          |    total    |     %     |
| ---------------------- | ----------- | --------- |
|         Thena          |  1,000.000  |  100.00%  |
```
### Test inactive account without ignore flag
input config:
```
{
  "allocationPolicies": [
    {
      "policyType": "SPECIAL",
      "memo": "test",
      "budget": 1000,
      "recipient": "6XoP0YuaULs3BWR6QaKmpg"
    }
  ],
  "maxSimultaneousDistributions": 100
}
```
Output:
```
Error: no active grain account for identity: 6XoP0YuaULs3BWR6QaKmpg
    at specialReceipts (webpack:///./src/core/ledger/policies/special.js?:18:281)
    at receipts (webpack:///./src/core/ledger/grainAllocation.js?:16:830)
    at computeAllocation (webpack:///./src/core/ledger/grainAllocation.js?:15:296)
```
### Test inactive with ignore flag
input config:
```
{
  "allocationPolicies": [
    {
      "policyType": "SPECIAL",
      "memo": "test",
      "budget": 1000,
      "recipient": "6XoP0YuaULs3BWR6QaKmpg",
      "ignoreActiveStatus": true
    }
  ],
  "maxSimultaneousDistributions": 100
}

```
Output:
```
SPECIAL Policy
Budget 1,000.000g
Memo: test
Recepient: 6XoP0YuaULs3BWR6QaKmpg
IgnoreActiveStatus: true
|          name          |    total    |     %     |
| ---------------------- | ----------- | --------- |
|     buffalonetwork     |  1,000.000  |  100.00%  |
```

2021-08-20 17:34 UTC, decentralion reviewed
The PR says it's adding the `ignoreActiveStatus` option, but it doesn't describe what this option does or why it's needed to accomplish the stated goals. Please update the description so that as a reviewer, I can understand what's happening technically.

I'm not really watching GH notifications, so please ping on Discord when this is ready for re-review.

2021-08-20 20:39 UTC, decentralion requested changes
The active/inactive distinction was added on the basis that receiving Grain can trigger legal/tax complications, and so participants cannot recieve Grain unless they've actively consented to that by marking themselves as active. This change would circumvent user consent and enable the project to pay people regardless of their wishes. I see it as misaligned with our values so it's a block from me. I have no objection to paying people through the special policy, but they should have marked themselves active first.

2021-08-20 20:46 UTC, blueridger commented
Discussed offline. @decentralion suggested the alternative of adding an "exclude" ID array field to the recent policy, since that covers the use case more accurately, and doesn't corrupt the invariant that "inactive == blocked from any grain activity"

2021-08-20 20:46 UTC, closed without merging

2021-09-09 18:32 UTC, blueridger commented
Created issue for exclusion field: https://github.com/sourcecred/sourcecred/issues/3185